Increase reproducibility of relative artefacts

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -691,6 +691,9 @@ build_os
 build_vendor
 build_cpu
 build
+build_map_flags
+srcdir_abs_real
+srcdir_abs
 target_libdir_is_relative
 target_bindir
 QS
@@ -2771,6 +2774,9 @@ profinfo_width=0
 extralibs=
 bootstrapping_flexdll=false
 target_libdir_is_relative=false
+srcdir_abs=''
+srcdir_abs_real=''
+build_map_flags=''
 
 # Information about the package
 
@@ -2875,6 +2881,9 @@ VERSION=4.08.2+relocatable
 
 
  # TODO: rename this variable
+
+
+
 
 
 
@@ -12423,8 +12432,8 @@ esac
 # See https://lists.gnu.org/archive/html/autoconf/2019-07/msg00002.html
 # for the detailed explanation.
 
-ocamlsrcdir=$(unset CDPATH; cd -- "$srcdir" && printf %sX "$PWD") || fail
-ocamlsrcdir=${ocamlsrcdir%X}
+srcdir_abs=$(unset CDPATH; cd -- "$srcdir" && printf %sX "$PWD") || fail
+srcdir_abs=${srcdir_abs%X}
 
 # Libraries to build depending on the host
 
@@ -12444,13 +12453,14 @@ fi
 $as_echo "$ln" >&6; }
 
     default_separator='\'
-    ocamlsrcdir="$(LC_ALL=C.UTF-8 cygpath -w -- "$ocamlsrcdir")"
+    ocamlsrcdir="$(LC_ALL=C.UTF-8 cygpath -w -- "$srcdir_abs")"
     unixlib="win32unix"
     graphlib="win32graph"
     cc_profile='' ;; #(
   *) :
     unix_or_win32="unix"
   ln='ln -sf'
+  ocamlsrcdir="$srcdir_abs"
   default_separator='/'
   unixlib="unix"
   graphlib="graph"
@@ -15378,6 +15388,91 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
   CFLAGS="$saved_CFLAGS"
  ;;
 esac
+
+## -ffile-prefix-map support by the C compiler - used in the build, not by
+## the compiler
+if test x"$bindir_to_libdir" != 'x'; then :
+  srcdir_abs_real="$(realpath "$srcdir_abs" 2>/dev/null)"
+  if test x"$srcdir_abs_real" = "x$srcdir_abs"; then :
+  srcdir_abs_real=''
+fi
+  as_CACHEVAR=`$as_echo "ax_cv_check_cflags_$warn_error_flag_-Wa,--debug-prefix-map=old=new" | $as_tr_sh`
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking whether the C compiler accepts -Wa,--debug-prefix-map=old=new" >&5
+$as_echo_n "checking whether the C compiler accepts -Wa,--debug-prefix-map=old=new... " >&6; }
+if eval \${$as_CACHEVAR+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+
+  ax_check_save_flags=$CFLAGS
+  CFLAGS="$CFLAGS $warn_error_flag -Wa,--debug-prefix-map=old=new"
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_compile "$LINENO"; then :
+  eval "$as_CACHEVAR=yes"
+else
+  eval "$as_CACHEVAR=no"
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+  CFLAGS=$ax_check_save_flags
+fi
+eval ac_res=\$$as_CACHEVAR
+	       { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_res" >&5
+$as_echo "$ac_res" >&6; }
+if eval test \"x\$"$as_CACHEVAR"\" = x"yes"; then :
+  build_map_flags='-Wa,--debug-prefix-map='
+else
+  :
+fi
+
+  as_CACHEVAR=`$as_echo "ax_cv_check_cflags_$warn_error_flag_-ffile-prefix-map=old=new" | $as_tr_sh`
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking whether the C compiler accepts -ffile-prefix-map=old=new" >&5
+$as_echo_n "checking whether the C compiler accepts -ffile-prefix-map=old=new... " >&6; }
+if eval \${$as_CACHEVAR+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+
+  ax_check_save_flags=$CFLAGS
+  CFLAGS="$CFLAGS $warn_error_flag -ffile-prefix-map=old=new"
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_compile "$LINENO"; then :
+  eval "$as_CACHEVAR=yes"
+else
+  eval "$as_CACHEVAR=no"
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+  CFLAGS=$ax_check_save_flags
+fi
+eval ac_res=\$$as_CACHEVAR
+	       { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_res" >&5
+$as_echo "$ac_res" >&6; }
+if eval test \"x\$"$as_CACHEVAR"\" = x"yes"; then :
+  build_map_flags="$build_map_flags -ffile-prefix-map="
+else
+  if $cc_has_debug_prefix_map; then :
+  build_map_flags="$build_map_flags -fdebug-prefix-map="
+fi
+fi
+
+fi
 
 ## Does stat support nanosecond precision
 
