Merge the bytecode executable headers
camlheader no longer contains the full name of the runtime, instead the
first line begins #! (if shebang scripts are supported) or !# (to
indicate that an executable header follows). The rest of the line is the
directory containing the runtime files, which is used by ocamlc to
append the actual name of the runtime variant.

The executable header no longer contains any default path, and RNTM is
always required. The RNTM section is now only written when using an
executable header; tools/ocamlsize is updated to read display the shebang
line as the runtime; its "(default runtime)" is therefore corrected to
display "(custom runtime)" for `-custom` executables.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -777,6 +777,8 @@ build_os
 build_vendor
 build_cpu
 build
+target_bindir_exp
+bindir_exp
 ln
 QS
 compute_deps
@@ -827,6 +829,7 @@ natdynlink
 supports_shared_libraries
 mklib
 AR
+bin_sh
 shebangscripts
 long_shebang
 flexlink_flags
@@ -3296,7 +3299,10 @@ OCAML_VERSION_SHORT=5.0
 
 
 
+
  # TODO: rename this variable
+
+
 
 
 
@@ -3341,6 +3347,10 @@ ac_config_files="$ac_config_files Makefile.config"
 
 ac_config_files="$ac_config_files stdlib/sys.ml"
 
+ac_config_files="$ac_config_files stdlib/camlheader.shebang"
+
+ac_config_files="$ac_config_files stdlib/target_camlheader.shebang"
+
 ac_config_files="$ac_config_files manual/src/version.tex"
 
 ac_config_files="$ac_config_files manual/src/html_processing/src/common.ml"
@@ -3358,6 +3368,9 @@ ac_config_files="$ac_config_files otherlibs/dynlink/META"
 ac_config_files="$ac_config_files otherlibs/runtime_events/META"
 
 ac_config_files="$ac_config_files stdlib/META"
+
+
+ac_config_commands="$ac_config_commands shebang"
 
 
 # Definitions related to the version of OCaml
@@ -13503,6 +13516,7 @@ printf "%s\n" "$ac_cv_sys_interpreter" >&6; }
 interpval=$ac_cv_sys_interpreter
 
 
+bin_sh=''
 long_shebang=false
 if test "x$interpval" = "xyes"
 then :
@@ -13511,20 +13525,15 @@ then :
     shebangscripts=false ;; #(
   *) :
     shebangscripts=true
-       prev_exec_prefix="$exec_prefix"
-       if test "x$exec_prefix" = "xNONE"
+      bin_sh="$(command -v sh 2>/dev/null)"
+      if test x"$bin_sh" = 'x' || test x"${bin_sh#* }" != x"$bin_sh" \
+             || test "${#bin_sha}" -gt 125
 then :
-  exec_prefix="$prefix"
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: could not determine a shebang-compatible location of sh - #! scripts disabled" >&5
+printf "%s\n" "$as_me: WARNING: could not determine a shebang-compatible location of sh - #! scripts disabled" >&2;}
+        shebangscripts=false
+        bin_sh=''
 fi
-       eval "expanded_bindir=\"$bindir\""
-       exec_prefix="$prev_exec_prefix"
-       # Assume maximum shebang is 128 chars; less #!, /ocamlrun, an optional
-       # 1 char suffix and the \0 leaving 115 characters
-       if test "${#expanded_bindir}" -gt 115
-then :
-  long_shebang=true
-fi
-
      ;;
 esac
 else $as_nop
@@ -19485,6 +19494,22 @@ else $as_nop
   stdlib_manpages=false
 fi
 
+if test x"$bindir" = 'x${exec_prefix}/bin'
+then :
+  if test x"$exec_prefix" = 'xNONE'
+then :
+  if test x"$prefix" = 'xNONE'
+then :
+  bindir_exp="${ac_default_prefix}/bin"
+else $as_nop
+  bindir_exp="${prefix}/bin"
+fi
+else $as_nop
+  bindir_exp="${exec_prefix}/bin"
+fi
+fi
+target_bindir_exp="$bindir_exp"
+
 # Do not permanently cache the result of flexdll.h
 unset ac_cv_header_flexdll_h
 
@@ -20298,6 +20323,9 @@ cat >>$CONFIG_STATUS <<_ACEOF || ac_write_fail=1
 # INIT-COMMANDS
 #
 
+  sed -e 's/bindir_exp/target_&/' stdlib/camlheader.shebang.in \
+    > stdlib/target_camlheader.shebang.in
+
 
 # The HP-UX ksh and POSIX shell print the target directory to stdout
 # if CDPATH is set.
@@ -20592,6 +20620,8 @@ do
     "Makefile.build_config") CONFIG_FILES="$CONFIG_FILES Makefile.build_config" ;;
     "Makefile.config") CONFIG_FILES="$CONFIG_FILES Makefile.config" ;;
     "stdlib/sys.ml") CONFIG_FILES="$CONFIG_FILES stdlib/sys.ml" ;;
+    "stdlib/camlheader.shebang") CONFIG_FILES="$CONFIG_FILES stdlib/camlheader.shebang" ;;
+    "stdlib/target_camlheader.shebang") CONFIG_FILES="$CONFIG_FILES stdlib/target_camlheader.shebang" ;;
     "manual/src/version.tex") CONFIG_FILES="$CONFIG_FILES manual/src/version.tex" ;;
     "manual/src/html_processing/src/common.ml") CONFIG_FILES="$CONFIG_FILES manual/src/html_processing/src/common.ml" ;;
     "runtime/caml/m.h") CONFIG_HEADERS="$CONFIG_HEADERS runtime/caml/m.h" ;;
@@ -20601,6 +20631,7 @@ do
     "otherlibs/dynlink/META") CONFIG_FILES="$CONFIG_FILES otherlibs/dynlink/META" ;;
     "otherlibs/runtime_events/META") CONFIG_FILES="$CONFIG_FILES otherlibs/runtime_events/META" ;;
     "stdlib/META") CONFIG_FILES="$CONFIG_FILES stdlib/META" ;;
+    "shebang") CONFIG_COMMANDS="$CONFIG_COMMANDS shebang" ;;
     "libtool") CONFIG_COMMANDS="$CONFIG_COMMANDS libtool" ;;
     "otherlibs/unix/META") CONFIG_FILES="$CONFIG_FILES otherlibs/unix/META" ;;
     "otherlibs/str/META") CONFIG_FILES="$CONFIG_FILES otherlibs/str/META" ;;
