[BACKPORT] Merge pull request PR#11240 from shindere/simplify-runtime-makefile
Simplify runtime/Makefile

diff --git a/diff-against-4.14-runtime.diff b/diff-against-4.14-runtime.diff
--- a/diff-against-4.14-runtime.diff
+++ b/diff-against-4.14-runtime.diff
@@ -381,7 +381,7 @@ index 0000000000..0ee84a6a5c
 +want to run them directly, in particular they will `git clean -xfd`,
 +destroying changed/uncommited files in your development repository!)
 diff --git a/runtime/Makefile b/runtime/Makefile
-index f5c08d8798..dee25dc02a 100644
+index f5c08d8798..8dd2240658 100644
 --- a/runtime/Makefile
 +++ b/runtime/Makefile
 @@ -26,7 +26,7 @@ BYTECODE_C_SOURCES := $(addsuffix .c, \
@@ -402,7 +402,89 @@ index f5c08d8798..dee25dc02a 100644
  
  # Header files generated by configure
  CONFIGURED_HEADERS := caml/m.h caml/s.h caml/version.h
-@@ -199,9 +199,9 @@ ld.conf: $(ROOTDIR)/Makefile.config
+@@ -43,14 +43,6 @@ CONFIGURED_HEADERS := caml/m.h caml/s.h caml/version.h
+ # Header files generated by make
+ BUILT_HEADERS := caml/opnames.h caml/jumptbl.h build_config.h
+ 
+-ifeq "$(TOOLCHAIN)" "msvc"
+-ASM_EXT := asm
+-ASM_SOURCES := $(ARCH)nt.$(ASM_EXT)
+-else
+-ASM_EXT := S
+-ASM_SOURCES := $(ARCH).$(ASM_EXT)
+-endif
+-
+ # Targets to build and install
+ 
+ PROGRAMS := ocamlrun$(EXE)
+@@ -82,8 +74,6 @@ endif
+ 
+ # List of object files for each target
+ 
+-ASM_OBJECTS := $(ASM_SOURCES:.$(ASM_EXT)=.$(O))
+-
+ libcamlrun_OBJECTS := $(BYTECODE_C_SOURCES:.c=.b.$(O))
+ 
+ libcamlrun_non_shared_OBJECTS := \
+@@ -97,51 +87,24 @@ libcamlruni_OBJECTS := $(BYTECODE_C_SOURCES:.c=.bi.$(O))
+ 
+ libcamlrunpic_OBJECTS := $(BYTECODE_C_SOURCES:.c=.bpic.$(O))
+ 
+-libasmrun_OBJECTS := $(NATIVE_C_SOURCES:.c=.n.$(O)) $(ASM_OBJECTS)
++libasmrun_OBJECTS := $(NATIVE_C_SOURCES:.c=.n.$(O)) $(runtime_ASM_OBJECTS)
+ 
+-libasmrund_OBJECTS := $(NATIVE_C_SOURCES:.c=.nd.$(O)) $(ASM_OBJECTS)
++libasmrund_OBJECTS := \
++  $(NATIVE_C_SOURCES:.c=.nd.$(O)) $(runtime_ASM_OBJECTS:.$(O)=.d.$(O))
+ 
+-libasmruni_OBJECTS := $(NATIVE_C_SOURCES:.c=.ni.$(O)) $(ASM_OBJECTS)
++libasmruni_OBJECTS := \
++  $(NATIVE_C_SOURCES:.c=.ni.$(O)) $(runtime_ASM_OBJECTS:.$(O)=.i.$(O))
+ 
+ libasmrunpic_OBJECTS := $(NATIVE_C_SOURCES:.c=.npic.$(O)) \
+-  $(ASM_OBJECTS:.$(O)=_libasmrunpic.$(O))
++  $(runtime_ASM_OBJECTS:.$(O)=_libasmrunpic.$(O))
+ 
+ # General (non target-specific) assembler and compiler flags
+ 
+-ifneq "$(CCOMPTYPE)" "msvc"
+-OC_CFLAGS += -g
+-endif
+-
+ OC_CPPFLAGS += -DCAMLDLLIMPORT=
+ 
+-OC_NATIVE_CPPFLAGS = -DNATIVE_CODE -DTARGET_$(ARCH)
+-
+-ifeq "$(UNIX_OR_WIN32)" "unix"
+-OC_NATIVE_CPPFLAGS += -DMODEL_$(MODEL)
+-endif
+-
+-OC_NATIVE_CPPFLAGS += -DSYS_$(SYSTEM)
+-
+ OC_DEBUG_CPPFLAGS=-DDEBUG
+ OC_INSTR_CPPFLAGS=-DCAML_INSTR
+ 
+-ifeq "$(TOOLCHAIN)" "msvc"
+-ASMFLAGS=
+-endif
+-
+-ASPPFLAGS = -DSYS_$(SYSTEM) -I$(ROOTDIR)/runtime
+-ifeq "$(UNIX_OR_WIN32)" "unix"
+-ASPPFLAGS += -DMODEL_$(MODEL)
+-endif
+-
+-# Commands used to build native libraries
+-
+-LIBS := $(BYTECCLIBS)
+-
+-ifeq "$(UNIX_OR_WIN32)" "win32"
+-LIBS += $(EXTRALIBS)
+-endif
+-
+ # Build, install and clean targets
+ 
+ .PHONY: all
+@@ -199,9 +162,9 @@ ld.conf: $(ROOTDIR)/Makefile.config
  # CAMLprim value caml_foo() ...
  # #else
  # CAMLprim value caml_foo() ...
@@ -414,6 +496,91 @@ index f5c08d8798..dee25dc02a 100644
  # We sort the primitive file and remove duplicates to avoid this problem.
  
  # Warning: we use "sort | uniq" instead of "sort -u" because in the MSVC
+@@ -265,10 +228,10 @@ build_config.h: $(ROOTDIR)/Makefile.config sak$(EXE)
+ # Libraries and programs
+ 
+ ocamlrun$(EXE): prims.$(O) libcamlrun.$(A)
+-	$(MKEXE) -o $@ $^ $(LIBS)
++	$(MKEXE) -o $@ $^ $(BYTECCLIBS)
+ 
+ ocamlruns$(EXE): prims.$(O) libcamlrun_non_shared.$(A)
+-	$(call MKEXE_USING_COMPILER,$@,$^ $(LIBS))
++	$(call MKEXE_USING_COMPILER,$@,$^ $(BYTECCLIBS))
+ 
+ libcamlrun.$(A): $(libcamlrun_OBJECTS)
+ 	$(call MKLIB,$@, $^)
+@@ -277,13 +240,13 @@ libcamlrun_non_shared.$(A): $(libcamlrun_non_shared_OBJECTS)
+ 	$(call MKLIB,$@, $^)
+ 
+ ocamlrund$(EXE): prims.$(O) libcamlrund.$(A)
+-	$(MKEXE) $(MKEXEDEBUGFLAG) -o $@ $^ $(LIBS)
++	$(MKEXE) $(MKEXEDEBUGFLAG) -o $@ $^ $(BYTECCLIBS)
+ 
+ libcamlrund.$(A): $(libcamlrund_OBJECTS)
+ 	$(call MKLIB,$@, $^)
+ 
+ ocamlruni$(EXE): prims.$(O) libcamlruni.$(A)
+-	$(MKEXE) -o $@ $^ $(INSTRUMENTED_RUNTIME_LIBS) $(LIBS)
++	$(MKEXE) -o $@ $^ $(INSTRUMENTED_RUNTIME_LIBS) $(BYTECCLIBS)
+ 
+ libcamlruni.$(A): $(libcamlruni_OBJECTS)
+ 	$(call MKLIB,$@, $^)
+@@ -375,15 +338,22 @@ $(foreach object_type,$(subst %,,$(object_types)), \
+ 
+ # Compilation of assembly files
+ 
+-%.o: %.S
+-	$(ASPP) $(ASPPFLAGS) -o $@ $< || \
+-	{ echo "If your assembler produced syntax errors, it is probably";\
++ASPP_ERROR = \
++  { echo "If your assembler produced syntax errors, it is probably";\
+           echo "unhappy with the preprocessor. Check your assembler, or";\
+           echo "try producing $*.o by hand.";\
+           exit 2; }
++%.o: %.S
++	$(ASPP) $(OC_ASPPFLAGS) -o $@ $< || $(ASPP_ERROR)
++
++%.d.o: %.S
++	$(ASPP) $(OC_ASPPFLAGS) $(OC_DEBUG_CPPFLAGS) -o $@ $< || $(ASPP_ERROR)
++
++%.i.o: %.S
++	$(ASPP) $(OC_ASPPFLAGS) $(OC_INSTR_CPPFLAGS) -o $@ $< || $(ASPP_ERROR)
+ 
+ %_libasmrunpic.o: %.S
+-	$(ASPP) $(ASPPFLAGS) $(SHAREDLIB_CFLAGS) -o $@ $<
++	$(ASPP) $(OC_ASPPFLAGS) $(SHAREDLIB_CFLAGS) -o $@ $<
+ 
+ domain_state64.inc: caml/domain_state.tbl gen_domain_state64_inc.awk
+ 	$(AWK) -f ./gen_domain_state64_inc.awk $< > $@
+@@ -392,13 +362,25 @@ domain_state32.inc: caml/domain_state.tbl gen_domain_state32_inc.awk
+ 	$(AWK) -f ./gen_domain_state32_inc.awk $< > $@
+ 
+ amd64nt.obj: amd64nt.asm domain_state64.inc
+-	$(ASM)$@ $(ASMFLAGS) $<
++	$(ASM)$@ $<
+ 
+ i386nt.obj: i386nt.asm domain_state32.inc
+-	$(ASM)$@ $(ASMFLAGS) $<
++	$(ASM)$@ $<
++
++amd64nt.d.obj: amd64nt.asm domain_state64.inc
++	$(ASM)$@ $(OC_DEBUG_CPPFLAGS) $<
++
++i386nt.d.obj: i386nt.asm domain_state32.inc
++	$(ASM)$@ $(OC_DEBUG_CPPFLAGS) $<
++
++amd64nt.i.obj: amd64nt.asm domain_state64.inc
++	$(ASM)$@ $(OC_INSTR_CPPFLAGS) $<
++
++i386nt.i.obj: i386nt.asm domain_state32.inc
++	$(ASM)$@ $(OC_INSTR_CPPFLAGS) $<
+ 
+ %_libasmrunpic.obj: %.asm
+-	$(ASM)$@ $(ASMFLAGS) $<
++	$(ASM)$@ $<
+ 
+ # Dependencies
+ 
 diff --git a/runtime/bigarray.c b/runtime/bigarray.c
 index ed4ff67d21..03151f6946 100644
 --- a/runtime/bigarray.c
