Do not return 0 on ENOENT in win32:caml_read_directory (PR#11866)
Fixes PR#11829

diff --git a/diff-against-trunk-system.diff b/diff-against-trunk-system.diff
--- a/diff-against-trunk-system.diff
+++ b/diff-against-trunk-system.diff
@@ -1,110 +1,21 @@
 diff --git a/.Diff-of-diff.diff b/.Diff-of-diff.diff
 new file mode 100644
-index 0000000000..f9111f994c
+index 0000000000..3a80cc3c92
 --- /dev/null
 +++ b/.Diff-of-diff.diff
-@@ -0,0 +1,101 @@
-+--- a	2023-09-28 18:46:47.222970579 +0100
-++++ b	2023-09-28 18:46:47.246971472 +0100
-+@@ -84,7 +84,7 @@
-+  	$(OCAMLRUN) $(cvt_emit) < $< >> $@ \
-+  	|| { rm -f $@; exit 2; }
-+  
-+-@@ -765,7 +765,7 @@ endif
-++@@ -762,7 +762,7 @@ endif
-+  ## Generated non-object files
-+  
-+  runtime/ld.conf: $(ROOTDIR)/Makefile.config
-+@@ -93,7 +93,7 @@
-+  	echo "$(LIBDIR)" >> $@
-+  
-+  # If primitives contain duplicated lines (e.g. because the code is defined
-+-@@ -793,10 +793,10 @@ runtime/primitives: \
-++@@ -790,10 +790,10 @@ runtime/primitives: \
-+    $(shell runtime/gen_primitives.sh > runtime/primitives.new; \
-+                      cmp -s runtime/primitives runtime/primitives.new || \
-+                      echo runtime/primitives.new)
-+@@ -106,7 +106,7 @@
-+  	(echo '#include "caml/config.h"'; \
-+  	 echo 'typedef intnat value;'; \
-+  	 echo 'typedef value (*c_primitive)(void);'; \
-+-@@ -812,7 +812,7 @@ runtime/prims.c : runtime/primitives
-++@@ -809,7 +809,7 @@ runtime/prims.c : runtime/primitives
-+  	 echo '  0 };') > $@
-+  
-+  runtime/caml/opnames.h : runtime/caml/instruct.h
-+@@ -115,7 +115,7 @@
-+  	sed -e '/\/\*/d' \
-+  	    -e '/^#/d' \
-+  	    -e 's/enum /static char * names_of_/' \
-+-@@ -821,7 +821,7 @@ runtime/caml/opnames.h : runtime/caml/instruct.h
-++@@ -818,7 +818,7 @@ runtime/caml/opnames.h : runtime/caml/instruct.h
-+  
-+  # runtime/caml/jumptbl.h is required only if you have GCC 2.0 or later
-+  runtime/caml/jumptbl.h : runtime/caml/instruct.h
-+@@ -124,7 +124,7 @@
-+  	sed -n -e '/^  /s/ \([A-Z]\)/ \&\&lbl_\1/gp' \
-+  	       -e '/^}/q' > $@
-+  
-+-@@ -832,64 +832,64 @@ SAK_CFLAGS ?= $(OC_CFLAGS) $(CFLAGS) $(OC_CPPFLAGS) $(CPPFLAGS)
-++@@ -829,64 +829,64 @@ SAK_CFLAGS ?= $(OC_CFLAGS) $(CFLAGS) $(OC_CPPFLAGS) $(CPPFLAGS)
-+  SAK_LINK ?= $(MKEXE_VIA_CC)
-+  
-+  $(SAK): runtime/sak.$(O)
-+@@ -208,7 +208,7 @@
-+  
-+  ## Runtime target-specific preprocessor and compiler flags
-+  
-+-@@ -936,7 +936,7 @@ ifneq "$(1)" "%"
-++@@ -933,7 +933,7 @@ ifneq "$(1)" "%"
-+  # instead include $(runtime_BUILT_HEADERS) in the order only dependencies
-+  # to ensure that they exist before dependencies are computed.
-+  $(DEPDIR)/$(1).$(D): runtime/%.c | $(DEPDIR)/runtime $(runtime_BUILT_HEADERS)
-+@@ -217,7 +217,7 @@
-+  	  'runtime/$$*$(subst runtime/%,,$(1)).$(O)' -MF $$@
-+  endif # ifneq "$(1)" "%"
-+  $(1).$(O): $(2).c
-+-@@ -945,7 +945,7 @@ $(1).$(O): $(2).c \
-++@@ -942,7 +942,7 @@ $(1).$(O): $(2).c \
-+    $(runtime_CONFIGURED_HEADERS) $(runtime_BUILT_HEADERS) \
-+    $(RUNTIME_HEADERS)
-+  endif # ifeq "$(COMPUTE_DEPS)" "true"
-+@@ -226,7 +226,7 @@
-+  	  $$(OUTPUTOBJ)$$@ $$<
-+  endef
-+  
-+-@@ -978,45 +978,45 @@ ASPP_ERROR = \
-++@@ -975,45 +975,45 @@ ASPP_ERROR = \
-+            echo "try producing $*.o by hand.";\
-+            exit 2; }
-+  runtime/%.o: runtime/%.S
-+@@ -285,7 +285,7 @@
-+  
-+  ## Runtime dependencies
-+  
-+-@@ -1148,7 +1148,7 @@ ocamlyacc_CPPFLAGS = -DNDEBUG
-++@@ -1147,7 +1147,7 @@ ocamlyacc_CPPFLAGS = -DNDEBUG
-+  ocamlyacc: $(ocamlyacc_PROGRAM)$(EXE)
-+  
-+  $(ocamlyacc_PROGRAM)$(EXE): $(ocamlyacc_OBJECTS)
-+@@ -293,7 +293,7 @@
-+ +	$(V_MKEXE)$(MKEXE) -o $@ $^
-+  
-+  clean::
-+- 	rm -f $(ocamlyacc_MODULES:=.o) $(ocamlyacc_MODULES:=.obj)
-++ 	rm -f yacc/wstr.o yacc/wstr.obj
-+ @@ -1180,9 +1180,9 @@ include Makefile.menhir
-+  # generated parser.ml.
-+  
-+@@ -1255,6 +1255,6 @@
-+  depend:
-+ -	{ \
-+ +	$(V_OCAMLDEP){ \
-+- 	  $(OCAMLDEP_CMD) $(filter-out stdlib.%,$(wildcard *.mli *.ml)); \
-++ 	  $(OCAMLDEP_CMD) $(filter-out stdlib.%,std_exit.ml std_exit.mli \
-++       $(STDLIB_MODULE_BASENAMES:=.mli) $(STDLIB_MODULE_BASENAMES:=.ml)); \
-+  	  $(OCAMLDEP_CMD) -pp "$(AWK) -f ./remove_module_aliases.awk" \
-+- 	  stdlib.ml stdlib.mli; \
+@@ -0,0 +1,12 @@
++--- a	2023-09-28 18:46:47.594984418 +0100
+++++ b	2023-09-28 18:46:47.614985162 +0100
++@@ -9,6 +9,6 @@
++ +  (Andrei Paskevich and Charlène Gros, review by David Allsopp and
++ +   Nicolás Ojeda Bär)
++ +
++- OCaml 5.0
++- ---------
++- 
+++ - #12264, #12289: Fix compact_allocate to avoid a pathological case
+++   that causes very slow compaction.
+++   (Damien Doligez, report by Arseniy Alekseyev, review by Sadiq Jaffer)
 diff --git a/.gitattributes b/.gitattributes
 index c972b3bc0b..18b5a6ee4f 100644
 --- a/.gitattributes
@@ -118,12 +29,12 @@ index c972b3bc0b..18b5a6ee4f 100644
  # TODO we should fix the long-line errors in yacc/*.c
  /yacc/*.[ch]         typo.very-long-line=may
 diff --git a/Changes b/Changes
-index eaa95f054a..c9aed43f72 100644
+index 8357076e8d..2bedd12948 100644
 --- a/Changes
 +++ b/Changes
-@@ -431,6 +431,10 @@ Working version
-   temporary assembly file is no longer left in the file system.
-   (Nicolás Ojeda Bär, review by Gabriel Scherer and Xavier Leroy)
+@@ -435,6 +435,10 @@ Working version
+   (Andrei Paskevich and Charlène Gros, review by David Allsopp and
+    Nicolás Ojeda Bär)
  
 +- #12264, #12289: Fix compact_allocate to avoid a pathological case
 +  that causes very slow compaction.
@@ -132,7 +43,7 @@ index eaa95f054a..c9aed43f72 100644
  OCaml 5.0
  ---------
  
-@@ -964,11 +968,6 @@ OCaml 5.0
+@@ -968,11 +972,6 @@ OCaml 5.0
    (Damien Doligez, report by Thierry Martinez and Vincent Laviron, review by
     Xavier Leroy)
  
@@ -144,7 +55,7 @@ index eaa95f054a..c9aed43f72 100644
  - #11516, #11524: Fix the `deprecated_mutable` attribute.
    (Chris Casinghino, review by Nicolás Ojeda Bär and Florian Angeletti)
  
-@@ -997,6 +996,30 @@ OCaml 5.0
+@@ -1001,6 +1000,30 @@ OCaml 5.0
    (Gabriel Scherer, review by Jacques Garrigue and Florian Angeletti,
     report by Yaron Minsky)
  
@@ -175,7 +86,7 @@ index eaa95f054a..c9aed43f72 100644
  OCaml 4.14.0 (28 March 2022)
  ----------------------------
  
-@@ -1032,13 +1055,13 @@ OCaml 4.14.0 (28 March 2022)
+@@ -1036,13 +1059,13 @@ OCaml 4.14.0 (28 March 2022)
  - #10549: Stack overflow detection and naked pointers checking for ARM64
    (Xavier Leroy, review by Stephen Dolan)
  
@@ -191,7 +102,7 @@ index eaa95f054a..c9aed43f72 100644
     code or an OCaml thread stops
    (Xavier Leroy, review by David Allsopp and Damien Doligez)
  
-@@ -1145,6 +1168,9 @@ OCaml 4.14.0 (28 March 2022)
+@@ -1149,6 +1172,9 @@ OCaml 4.14.0 (28 March 2022)
  - #10464: Add List.is_empty.
    (Craig Ferguson, review by David Allsopp)
  
@@ -201,7 +112,7 @@ index eaa95f054a..c9aed43f72 100644
  ### Other libraries:
  
  - #10192: Add support for Unix domain sockets on Windows and use them
-@@ -1404,6 +1430,9 @@ OCaml 4.14.0 (28 March 2022)
+@@ -1408,6 +1434,9 @@ OCaml 4.14.0 (28 March 2022)
  
  ### Build system:
  
@@ -10236,117 +10147,28 @@ index 0000000000..d618ab8beb
 +     fi
 diff --git a/diff-against-trunk-system.diff b/diff-against-trunk-system.diff
 new file mode 100644
-index 0000000000..2e380f79d7
+index 0000000000..eaf232eba0
 --- /dev/null
 +++ b/diff-against-trunk-system.diff
-@@ -0,0 +1,10137 @@
+@@ -0,0 +1,10145 @@
 +diff --git a/.Diff-of-diff.diff b/.Diff-of-diff.diff
 +new file mode 100644
-+index 0000000000..f9111f994c
++index 0000000000..3a80cc3c92
 +--- /dev/null
 ++++ b/.Diff-of-diff.diff
-+@@ -0,0 +1,101 @@
-++--- a	2023-09-28 18:46:47.222970579 +0100
-+++++ b	2023-09-28 18:46:47.246971472 +0100
-++@@ -84,7 +84,7 @@
-++  	$(OCAMLRUN) $(cvt_emit) < $< >> $@ \
-++  	|| { rm -f $@; exit 2; }
-++  
-++-@@ -765,7 +765,7 @@ endif
-+++@@ -762,7 +762,7 @@ endif
-++  ## Generated non-object files
-++  
-++  runtime/ld.conf: $(ROOTDIR)/Makefile.config
-++@@ -93,7 +93,7 @@
-++  	echo "$(LIBDIR)" >> $@
-++  
-++  # If primitives contain duplicated lines (e.g. because the code is defined
-++-@@ -793,10 +793,10 @@ runtime/primitives: \
-+++@@ -790,10 +790,10 @@ runtime/primitives: \
-++    $(shell runtime/gen_primitives.sh > runtime/primitives.new; \
-++                      cmp -s runtime/primitives runtime/primitives.new || \
-++                      echo runtime/primitives.new)
-++@@ -106,7 +106,7 @@
-++  	(echo '#include "caml/config.h"'; \
-++  	 echo 'typedef intnat value;'; \
-++  	 echo 'typedef value (*c_primitive)(void);'; \
-++-@@ -812,7 +812,7 @@ runtime/prims.c : runtime/primitives
-+++@@ -809,7 +809,7 @@ runtime/prims.c : runtime/primitives
-++  	 echo '  0 };') > $@
-++  
-++  runtime/caml/opnames.h : runtime/caml/instruct.h
-++@@ -115,7 +115,7 @@
-++  	sed -e '/\/\*/d' \
-++  	    -e '/^#/d' \
-++  	    -e 's/enum /static char * names_of_/' \
-++-@@ -821,7 +821,7 @@ runtime/caml/opnames.h : runtime/caml/instruct.h
-+++@@ -818,7 +818,7 @@ runtime/caml/opnames.h : runtime/caml/instruct.h
-++  
-++  # runtime/caml/jumptbl.h is required only if you have GCC 2.0 or later
-++  runtime/caml/jumptbl.h : runtime/caml/instruct.h
-++@@ -124,7 +124,7 @@
-++  	sed -n -e '/^  /s/ \([A-Z]\)/ \&\&lbl_\1/gp' \
-++  	       -e '/^}/q' > $@
-++  
-++-@@ -832,64 +832,64 @@ SAK_CFLAGS ?= $(OC_CFLAGS) $(CFLAGS) $(OC_CPPFLAGS) $(CPPFLAGS)
-+++@@ -829,64 +829,64 @@ SAK_CFLAGS ?= $(OC_CFLAGS) $(CFLAGS) $(OC_CPPFLAGS) $(CPPFLAGS)
-++  SAK_LINK ?= $(MKEXE_VIA_CC)
-++  
-++  $(SAK): runtime/sak.$(O)
-++@@ -208,7 +208,7 @@
-++  
-++  ## Runtime target-specific preprocessor and compiler flags
-++  
-++-@@ -936,7 +936,7 @@ ifneq "$(1)" "%"
-+++@@ -933,7 +933,7 @@ ifneq "$(1)" "%"
-++  # instead include $(runtime_BUILT_HEADERS) in the order only dependencies
-++  # to ensure that they exist before dependencies are computed.
-++  $(DEPDIR)/$(1).$(D): runtime/%.c | $(DEPDIR)/runtime $(runtime_BUILT_HEADERS)
-++@@ -217,7 +217,7 @@
-++  	  'runtime/$$*$(subst runtime/%,,$(1)).$(O)' -MF $$@
-++  endif # ifneq "$(1)" "%"
-++  $(1).$(O): $(2).c
-++-@@ -945,7 +945,7 @@ $(1).$(O): $(2).c \
-+++@@ -942,7 +942,7 @@ $(1).$(O): $(2).c \
-++    $(runtime_CONFIGURED_HEADERS) $(runtime_BUILT_HEADERS) \
-++    $(RUNTIME_HEADERS)
-++  endif # ifeq "$(COMPUTE_DEPS)" "true"
-++@@ -226,7 +226,7 @@
-++  	  $$(OUTPUTOBJ)$$@ $$<
-++  endef
-++  
-++-@@ -978,45 +978,45 @@ ASPP_ERROR = \
-+++@@ -975,45 +975,45 @@ ASPP_ERROR = \
-++            echo "try producing $*.o by hand.";\
-++            exit 2; }
-++  runtime/%.o: runtime/%.S
-++@@ -285,7 +285,7 @@
-++  
-++  ## Runtime dependencies
-++  
-++-@@ -1148,7 +1148,7 @@ ocamlyacc_CPPFLAGS = -DNDEBUG
-+++@@ -1147,7 +1147,7 @@ ocamlyacc_CPPFLAGS = -DNDEBUG
-++  ocamlyacc: $(ocamlyacc_PROGRAM)$(EXE)
-++  
-++  $(ocamlyacc_PROGRAM)$(EXE): $(ocamlyacc_OBJECTS)
-++@@ -293,7 +293,7 @@
-++ +	$(V_MKEXE)$(MKEXE) -o $@ $^
-++  
-++  clean::
-++- 	rm -f $(ocamlyacc_MODULES:=.o) $(ocamlyacc_MODULES:=.obj)
-+++ 	rm -f yacc/wstr.o yacc/wstr.obj
-++ @@ -1180,9 +1180,9 @@ include Makefile.menhir
-++  # generated parser.ml.
-++  
-++@@ -1255,6 +1255,6 @@
-++  depend:
-++ -	{ \
-++ +	$(V_OCAMLDEP){ \
-++- 	  $(OCAMLDEP_CMD) $(filter-out stdlib.%,$(wildcard *.mli *.ml)); \
-+++ 	  $(OCAMLDEP_CMD) $(filter-out stdlib.%,std_exit.ml std_exit.mli \
-+++       $(STDLIB_MODULE_BASENAMES:=.mli) $(STDLIB_MODULE_BASENAMES:=.ml)); \
-++  	  $(OCAMLDEP_CMD) -pp "$(AWK) -f ./remove_module_aliases.awk" \
-++- 	  stdlib.ml stdlib.mli; \
++@@ -0,0 +1,12 @@
+++--- a	2023-09-28 18:46:47.594984418 +0100
++++++ b	2023-09-28 18:46:47.614985162 +0100
+++@@ -9,6 +9,6 @@
+++ +  (Andrei Paskevich and Charlène Gros, review by David Allsopp and
+++ +   Nicolás Ojeda Bär)
+++ +
+++- OCaml 5.0
+++- ---------
+++- 
++++ - #12264, #12289: Fix compact_allocate to avoid a pathological case
++++   that causes very slow compaction.
++++   (Damien Doligez, report by Arseniy Alekseyev, review by Sadiq Jaffer)
 +diff --git a/.gitattributes b/.gitattributes
 +index c972b3bc0b..18b5a6ee4f 100644
 +--- a/.gitattributes
@@ -10360,12 +10182,12 @@ index 0000000000..2e380f79d7
 + # TODO we should fix the long-line errors in yacc/*.c
 + /yacc/*.[ch]         typo.very-long-line=may
 +diff --git a/Changes b/Changes
-+index eaa95f054a..c9aed43f72 100644
++index 8357076e8d..2bedd12948 100644
 +--- a/Changes
 ++++ b/Changes
-+@@ -431,6 +431,10 @@ Working version
-+   temporary assembly file is no longer left in the file system.
-+   (Nicolás Ojeda Bär, review by Gabriel Scherer and Xavier Leroy)
++@@ -435,6 +435,10 @@ Working version
++   (Andrei Paskevich and Charlène Gros, review by David Allsopp and
++    Nicolás Ojeda Bär)
 + 
 ++- #12264, #12289: Fix compact_allocate to avoid a pathological case
 ++  that causes very slow compaction.
@@ -10374,7 +10196,7 @@ index 0000000000..2e380f79d7
 + OCaml 5.0
 + ---------
 + 
-+@@ -964,11 +968,6 @@ OCaml 5.0
++@@ -968,11 +972,6 @@ OCaml 5.0
 +   (Damien Doligez, report by Thierry Martinez and Vincent Laviron, review by
 +    Xavier Leroy)
 + 
@@ -10386,7 +10208,7 @@ index 0000000000..2e380f79d7
 + - #11516, #11524: Fix the `deprecated_mutable` attribute.
 +   (Chris Casinghino, review by Nicolás Ojeda Bär and Florian Angeletti)
 + 
-+@@ -997,6 +996,30 @@ OCaml 5.0
++@@ -1001,6 +1000,30 @@ OCaml 5.0
 +   (Gabriel Scherer, review by Jacques Garrigue and Florian Angeletti,
 +    report by Yaron Minsky)
 + 
@@ -10417,7 +10239,7 @@ index 0000000000..2e380f79d7
 + OCaml 4.14.0 (28 March 2022)
 + ----------------------------
 + 
-+@@ -1032,13 +1055,13 @@ OCaml 4.14.0 (28 March 2022)
++@@ -1036,13 +1059,13 @@ OCaml 4.14.0 (28 March 2022)
 + - #10549: Stack overflow detection and naked pointers checking for ARM64
 +   (Xavier Leroy, review by Stephen Dolan)
 + 
@@ -10433,7 +10255,7 @@ index 0000000000..2e380f79d7
 +    code or an OCaml thread stops
 +   (Xavier Leroy, review by David Allsopp and Damien Doligez)
 + 
-+@@ -1145,6 +1168,9 @@ OCaml 4.14.0 (28 March 2022)
++@@ -1149,6 +1172,9 @@ OCaml 4.14.0 (28 March 2022)
 + - #10464: Add List.is_empty.
 +   (Craig Ferguson, review by David Allsopp)
 + 
@@ -10443,7 +10265,7 @@ index 0000000000..2e380f79d7
 + ### Other libraries:
 + 
 + - #10192: Add support for Unix domain sockets on Windows and use them
-+@@ -1404,6 +1430,9 @@ OCaml 4.14.0 (28 March 2022)
++@@ -1408,6 +1434,9 @@ OCaml 4.14.0 (28 March 2022)
 + 
 + ### Build system:
 + 
@@ -20376,7 +20198,104 @@ index 0000000000..2e380f79d7
 ++ 
 ++diff --git a/testsuite/tests/weak-ephe-final/weaklifetime_par.ml b/testsuite/tests/weak-ephe-final/weaklifetime_par.ml
 ++index b42d399907..656e318473 100644
-++--- a/t
+++--- a/testsuite/tests/weak-ephe-final/weaklifetime_par.ml
++++++ b/testsuite/tests/weak-ephe-final/weaklifetime_par.ml
+++@@ -1,3 +1,7 @@
++++(* TEST
++++   * skip
++++   reason = "OCaml 5 only"
++++*)
+++ (* This test is currently disabled,
+++    until the random failures have been investigated.
+++ *)
+++diff --git a/testsuite/tests/weak-ephe-final/weaktest_par_load.ml b/testsuite/tests/weak-ephe-final/weaktest_par_load.ml
+++index f5e0711b79..8beb1f6433 100644
+++--- a/testsuite/tests/weak-ephe-final/weaktest_par_load.ml
++++++ b/testsuite/tests/weak-ephe-final/weaktest_par_load.ml
+++@@ -1,4 +1,7 @@
+++-(* TEST *)
++++(* TEST
++++* skip
++++reason = "OCaml 5 only"
++++*)
+++ 
+++ (* Testing unsynchronized, parallel Weak usage *)
+++ 
+++diff --git a/testsuite/tools/asmgen_i386.S b/testsuite/tools/asmgen_i386.S
+++index 1d16b72d4e..956ec369ab 100644
+++--- a/testsuite/tools/asmgen_i386.S
++++++ b/testsuite/tools/asmgen_i386.S
+++@@ -49,7 +49,7 @@ G(call_gen_code):
+++ G(caml_c_call):
+++         jmp     *%eax
+++ 
+++-        .comm   G(Caml_state), 4
++++        .comm   G(caml_state), 4
+++ 
+++ /* Some tests are designed to cause registers to spill; on
+++  * x86 we require the caml_extra_params symbol from the RTS. */
+++diff --git a/tools/ci/actions/runner.sh b/tools/ci/actions/runner.sh
+++index de10bd1fd3..5f9e31bc66 100755
+++--- a/tools/ci/actions/runner.sh
++++++ b/tools/ci/actions/runner.sh
+++@@ -40,19 +40,7 @@ EOF
+++     --enable-debug-runtime \
+++     $CONFIG_ARG"
+++ 
+++-  case $XARCH in
+++-  x64)
+++-    ./configure $configure_flags
+++-    ;;
+++-  i386)
+++-    ./configure --build=x86_64-pc-linux-gnu --host=i386-pc-linux-gnu \
+++-      $configure_flags
+++-    ;;
+++-  *)
+++-    echo unknown arch
+++-    exit 1
+++-    ;;
+++-  esac
++++  ./configure $configure_flags
+++ }
+++ 
+++ Build () {
+++diff --git a/tools/ci/appveyor/appveyor_build.sh b/tools/ci/appveyor/appveyor_build.sh
+++index 3292ad9c31..24fd58adef 100644
+++--- a/tools/ci/appveyor/appveyor_build.sh
++++++ b/tools/ci/appveyor/appveyor_build.sh
+++@@ -64,8 +64,8 @@ function set_configuration {
+++         mingw64)
+++             build='--build=i686-pc-cygwin'
+++             host='--host=x86_64-w64-mingw32'
+++-            dep='--disable-dependency-generation'
+++-            man='--disable-stdlib-manpages'
++++            # Explicitly test dependency generation on msvc64
++++            dep='--enable-dependency-generation'
+++         ;;
+++         msvc32)
+++             build='--build=i686-pc-cygwin'
+++@@ -158,10 +158,13 @@ case "$1" in
+++     run "test $PORT" \
+++         make -C "$FULL_BUILD_PREFIX-$PORT/testsuite" SHOW_TIMINGS=1 all
+++     run "install $PORT" $MAKE -C "$FULL_BUILD_PREFIX-$PORT" install
+++-    if [[ $PORT = 'msvc64' ]] ; then
++++    if [[ $PORT = 'mingw64' ]] ; then
+++       run "$MAKE check_all_arches" \
+++            $MAKE -C "$FULL_BUILD_PREFIX-$PORT" check_all_arches
+++       cd "$FULL_BUILD_PREFIX-$PORT"
++++
++++      git config --global safe.directory '*'
++++
+++       # Ensure that .gitignore is up-to-date - this will fail if any untracked
+++       # or altered files exist. We revert the change from the bootstrap (that
+++       # would have failed the build earlier if necessary)
+++@@ -181,7 +184,7 @@ case "$1" in
+++   *)
+++     cd "$APPVEYOR_BUILD_FOLDER/../$BUILD_PREFIX-$PORT"
+++ 
+++-    if [[ $PORT = 'msvc64' ]] ; then
++++    if [[ $PORT = 'mingw64' ]] ; then
+++       # Ensure that 
 \ No newline at end of file
 diff --git a/lambda/matching.ml b/lambda/matching.ml
 index a155076b11..c4b0f00cc5 100644
