Merge pull request PR#11622 from Octachron/fix_recursive_types_in_constructor_mismatch
Printtyp: avoid stack overflow when printing constructors or records with recursive types in inclusion error messages

diff --git a/diff-against-trunk-system.diff b/diff-against-trunk-system.diff
--- a/diff-against-trunk-system.diff
+++ b/diff-against-trunk-system.diff
@@ -1,6 +1,31 @@
 diff --git a/.Diff-of-diff.diff b/.Diff-of-diff.diff
 new file mode 100644
-index 0000000000..e69de29bb2
+index 0000000000..c04ae329a4
+--- /dev/null
++++ b/.Diff-of-diff.diff
+@@ -0,0 +1,22 @@
++--- a	2023-09-28 18:45:52.060887441 +0100
+++++ b	2023-09-28 18:45:52.076888054 +0100
++@@ -1,7 +1,7 @@
++ diff --git a/Changes b/Changes
++ --- a/Changes
++ +++ b/Changes
++-@@ -682,6 +682,10 @@ OCaml 5.0
+++@@ -677,6 +677,10 @@ OCaml 5.0
++  - #11587: Prevent integer comparison from being used on pointers
++    (Vincent Laviron, review by Gabriel Scherer)
++  
++@@ -9,8 +9,8 @@
++ +  mismatch error involving recursive types.
++ +  (Florian Angeletti, review by Gabriel Scherer)
++ +
++- OCaml 4.14.0 (28 March 2022)
++- ----------------------------
+++ OCaml 4.14 maintenance branch
+++ -----------------------------
++  
++ diff --git a/testsuite/tests/typing-modules/inclusion_errors.ml b/testsuite/tests/typing-modules/inclusion_errors.ml
++ --- a/testsuite/tests/typing-modules/inclusion_errors.ml
 diff --git a/.gitattributes b/.gitattributes
 index cf76412e2b..c21c8f2bf4 100644
 --- a/.gitattributes
@@ -14,7 +39,7 @@ index cf76412e2b..c21c8f2bf4 100644
  # TODO we should fix the long-line errors in yacc/*.c
  /yacc/*.[ch]         typo.very-long-line=may
 diff --git a/Changes b/Changes
-index 7c9d51cccd..c8fc69ee7d 100644
+index 1e945b4057..e667db4d97 100644
 --- a/Changes
 +++ b/Changes
 @@ -666,11 +666,6 @@ OCaml 5.0
@@ -29,9 +54,9 @@ index 7c9d51cccd..c8fc69ee7d 100644
  - #11516, #11524: Fix the `deprecated_mutable` attribute.
    (Chris Casinghino, review by Nicolás Ojeda Bär and Florian Angeletti)
  
-@@ -682,6 +677,26 @@ OCaml 5.0
- - #11587: Prevent integer comparison from being used on pointers
-   (Vincent Laviron, review by Gabriel Scherer)
+@@ -686,6 +681,26 @@ OCaml 5.0
+   mismatch error involving recursive types.
+   (Florian Angeletti, review by Gabriel Scherer)
  
 +OCaml 4.14 maintenance branch
 +-----------------------------
@@ -56,7 +81,7 @@ index 7c9d51cccd..c8fc69ee7d 100644
  OCaml 4.14.0 (28 March 2022)
  ----------------------------
  
-@@ -717,13 +732,13 @@ OCaml 4.14.0 (28 March 2022)
+@@ -721,13 +736,13 @@ OCaml 4.14.0 (28 March 2022)
  - #10549: Stack overflow detection and naked pointers checking for ARM64
    (Xavier Leroy, review by Stephen Dolan)
  
@@ -72,7 +97,7 @@ index 7c9d51cccd..c8fc69ee7d 100644
     code or an OCaml thread stops
    (Xavier Leroy, review by David Allsopp and Damien Doligez)
  
-@@ -827,6 +842,9 @@ OCaml 4.14.0 (28 March 2022)
+@@ -831,6 +846,9 @@ OCaml 4.14.0 (28 March 2022)
  - #10786: The implementation of Complex.norm now uses Float.hypot.
    (Christophe Troestler, review by David Allsopp and Xavier Leroy)
  
@@ -82,7 +107,7 @@ index 7c9d51cccd..c8fc69ee7d 100644
  ### Other libraries:
  
  - #10192: Add support for Unix domain sockets on Windows and use them
-@@ -1086,6 +1104,9 @@ OCaml 4.14.0 (28 March 2022)
+@@ -1090,6 +1108,9 @@ OCaml 4.14.0 (28 March 2022)
  
  ### Build system:
  
@@ -10005,13 +10030,38 @@ index 0000000000..464eb345bc
 +     fi
 diff --git a/diff-against-trunk-system.diff b/diff-against-trunk-system.diff
 new file mode 100644
-index 0000000000..ae3c045e18
+index 0000000000..61362f2b7c
 --- /dev/null
 +++ b/diff-against-trunk-system.diff
-@@ -0,0 +1,9904 @@
+@@ -0,0 +1,10024 @@
 +diff --git a/.Diff-of-diff.diff b/.Diff-of-diff.diff
 +new file mode 100644
-+index 0000000000..e69de29bb2
++index 0000000000..c04ae329a4
++--- /dev/null
+++++ b/.Diff-of-diff.diff
++@@ -0,0 +1,22 @@
+++--- a	2023-09-28 18:45:52.060887441 +0100
++++++ b	2023-09-28 18:45:52.076888054 +0100
+++@@ -1,7 +1,7 @@
+++ diff --git a/Changes b/Changes
+++ --- a/Changes
+++ +++ b/Changes
+++-@@ -682,6 +682,10 @@ OCaml 5.0
++++@@ -677,6 +677,10 @@ OCaml 5.0
+++  - #11587: Prevent integer comparison from being used on pointers
+++    (Vincent Laviron, review by Gabriel Scherer)
+++  
+++@@ -9,8 +9,8 @@
+++ +  mismatch error involving recursive types.
+++ +  (Florian Angeletti, review by Gabriel Scherer)
+++ +
+++- OCaml 4.14.0 (28 March 2022)
+++- ----------------------------
++++ OCaml 4.14 maintenance branch
++++ -----------------------------
+++  
+++ diff --git a/testsuite/tests/typing-modules/inclusion_errors.ml b/testsuite/tests/typing-modules/inclusion_errors.ml
+++ --- a/testsuite/tests/typing-modules/inclusion_errors.ml
 +diff --git a/.gitattributes b/.gitattributes
 +index cf76412e2b..c21c8f2bf4 100644
 +--- a/.gitattributes
@@ -10025,7 +10075,7 @@ index 0000000000..ae3c045e18
 + # TODO we should fix the long-line errors in yacc/*.c
 + /yacc/*.[ch]         typo.very-long-line=may
 +diff --git a/Changes b/Changes
-+index 7c9d51cccd..c8fc69ee7d 100644
++index 1e945b4057..e667db4d97 100644
 +--- a/Changes
 ++++ b/Changes
 +@@ -666,11 +666,6 @@ OCaml 5.0
@@ -10040,9 +10090,9 @@ index 0000000000..ae3c045e18
 + - #11516, #11524: Fix the `deprecated_mutable` attribute.
 +   (Chris Casinghino, review by Nicolás Ojeda Bär and Florian Angeletti)
 + 
-+@@ -682,6 +677,26 @@ OCaml 5.0
-+ - #11587: Prevent integer comparison from being used on pointers
-+   (Vincent Laviron, review by Gabriel Scherer)
++@@ -686,6 +681,26 @@ OCaml 5.0
++   mismatch error involving recursive types.
++   (Florian Angeletti, review by Gabriel Scherer)
 + 
 ++OCaml 4.14 maintenance branch
 ++-----------------------------
@@ -10067,7 +10117,7 @@ index 0000000000..ae3c045e18
 + OCaml 4.14.0 (28 March 2022)
 + ----------------------------
 + 
-+@@ -717,13 +732,13 @@ OCaml 4.14.0 (28 March 2022)
++@@ -721,13 +736,13 @@ OCaml 4.14.0 (28 March 2022)
 + - #10549: Stack overflow detection and naked pointers checking for ARM64
 +   (Xavier Leroy, review by Stephen Dolan)
 + 
@@ -10083,7 +10133,7 @@ index 0000000000..ae3c045e18
 +    code or an OCaml thread stops
 +   (Xavier Leroy, review by David Allsopp and Damien Doligez)
 + 
-+@@ -827,6 +842,9 @@ OCaml 4.14.0 (28 March 2022)
++@@ -831,6 +846,9 @@ OCaml 4.14.0 (28 March 2022)
 + - #10786: The implementation of Complex.norm now uses Float.hypot.
 +   (Christophe Troestler, review by David Allsopp and Xavier Leroy)
 + 
@@ -10093,7 +10143,7 @@ index 0000000000..ae3c045e18
 + ### Other libraries:
 + 
 + - #10192: Add support for Unix domain sockets on Windows and use them
-+@@ -1086,6 +1104,9 @@ OCaml 4.14.0 (28 March 2022)
++@@ -1090,6 +1108,9 @@ OCaml 4.14.0 (28 March 2022)
 + 
 + ### Build system:
 + 
@@ -19912,7 +19962,102 @@ index 0000000000..ae3c045e18
 ++ 
 ++ let () = Out_channel.set_buffered stdout false
 ++ 
-++diff --git a/testsuite/tests/weak-ephe-final/finaliser_
+++diff --git a/testsuite/tests/weak-ephe-final/finaliser_handover.ml b/testsuite/tests/weak-ephe-final/finaliser_handover.ml
+++index fa2d2efc43..752a7eeabf 100644
+++--- a/testsuite/tests/weak-ephe-final/finaliser_handover.ml
++++++ b/testsuite/tests/weak-ephe-final/finaliser_handover.ml
+++@@ -1,4 +1,7 @@
+++-(* TEST *)
++++(* TEST
++++   * skip
++++   reason = "OCaml 5 only"
++++*)
+++ 
+++ (* ocaml-multicore issues 528 and 468 *)
+++ 
+++diff --git a/testsuite/tests/weak-ephe-final/weaklifetime_par.ml b/testsuite/tests/weak-ephe-final/weaklifetime_par.ml
+++index b42d399907..656e318473 100644
+++--- a/testsuite/tests/weak-ephe-final/weaklifetime_par.ml
++++++ b/testsuite/tests/weak-ephe-final/weaklifetime_par.ml
+++@@ -1,3 +1,7 @@
++++(* TEST
++++   * skip
++++   reason = "OCaml 5 only"
++++*)
+++ (* This test is currently disabled,
+++    until the random failures have been investigated.
+++ *)
+++diff --git a/testsuite/tools/asmgen_i386.S b/testsuite/tools/asmgen_i386.S
+++index 1d16b72d4e..956ec369ab 100644
+++--- a/testsuite/tools/asmgen_i386.S
++++++ b/testsuite/tools/asmgen_i386.S
+++@@ -49,7 +49,7 @@ G(call_gen_code):
+++ G(caml_c_call):
+++         jmp     *%eax
+++ 
+++-        .comm   G(Caml_state), 4
++++        .comm   G(caml_state), 4
+++ 
+++ /* Some tests are designed to cause registers to spill; on
+++  * x86 we require the caml_extra_params symbol from the RTS. */
+++diff --git a/tools/ci/actions/runner.sh b/tools/ci/actions/runner.sh
+++index de10bd1fd3..5f9e31bc66 100755
+++--- a/tools/ci/actions/runner.sh
++++++ b/tools/ci/actions/runner.sh
+++@@ -40,19 +40,7 @@ EOF
+++     --enable-debug-runtime \
+++     $CONFIG_ARG"
+++ 
+++-  case $XARCH in
+++-  x64)
+++-    ./configure $configure_flags
+++-    ;;
+++-  i386)
+++-    ./configure --build=x86_64-pc-linux-gnu --host=i386-pc-linux-gnu \
+++-      $configure_flags
+++-    ;;
+++-  *)
+++-    echo unknown arch
+++-    exit 1
+++-    ;;
+++-  esac
++++  ./configure $configure_flags
+++ }
+++ 
+++ Build () {
+++diff --git a/tools/ci/appveyor/appveyor_build.sh b/tools/ci/appveyor/appveyor_build.sh
+++index cdeaf1b674..832812925d 100644
+++--- a/tools/ci/appveyor/appveyor_build.sh
++++++ b/tools/ci/appveyor/appveyor_build.sh
+++@@ -64,8 +64,8 @@ function set_configuration {
+++         mingw64)
+++             build='--build=i686-pc-cygwin'
+++             host='--host=x86_64-w64-mingw32'
+++-            dep='--disable-dependency-generation'
+++-            man='--disable-stdlib-manpages'
++++            # Explicitly test dependency generation on msvc64
++++            dep='--enable-dependency-generation'
+++         ;;
+++         msvc32)
+++             build='--build=i686-pc-cygwin'
+++@@ -152,10 +152,13 @@ case "$1" in
+++     run "test $PORT" \
+++         make -C "$FULL_BUILD_PREFIX-$PORT/testsuite" SHOW_TIMINGS=1 all
+++     run "install $PORT" $MAKE -C "$FULL_BUILD_PREFIX-$PORT" install
+++-    if [[ $PORT = 'msvc64' ]] ; then
++++    if [[ $PORT = 'mingw64' ]] ; then
+++       run "$MAKE check_all_arches" \
+++            $MAKE -C "$FULL_BUILD_PREFIX-$PORT" check_all_arches
+++       cd "$FULL_BUILD_PREFIX-$PORT"
++++
++++      git config --global safe.directory '*'
++++
+++       # Ensure that .gitignore is up-to-date - this will fail if any untracked
+++       # or altered files exist. We revert the change from the bootstrap (that
+++       # would have failed the build earlier if necessary)
+++@@ -175,7 +178,7 @@ case "$1" in
+++   *)
+++     cd "$APPVEYOR_BUILD_FOLDER/../$
 \ No newline at end of file
 diff --git a/lambda/matching.ml b/lambda/matching.ml
 index a155076b11..c4b0f00cc5 100644
