Basis

diff --git a/Makefile.common b/Makefile.common
--- a/Makefile.common
+++ b/Makefile.common
@@ -27,14 +27,384 @@ MKDIR=mkdir -p
 EMPTY :=
 # $(SPACE) contains a single space
 SPACE := $(EMPTY) $(EMPTY)
+$(SPACE) :=
+HASH := \#
+
+ifeq "$(UNIX_OR_WIN32)" "win32"
+DIR_SEP := \$ # There must a space following the $
+CONVERT_PATH = $(subst /,$(DIR_SEP),$(strip $(1)))
+else
+DIR_SEP = /
+CONVERT_PATH = $(strip $(1))
+endif
+
+QUOTE_SINGLE = '$(subst ','\'',$(1))'
 
 DESTDIR ?=
-INSTALL_BINDIR := $(DESTDIR)$(BINDIR)
-INSTALL_LIBDIR := $(DESTDIR)$(LIBDIR)
-INSTALL_STUBLIBDIR := $(DESTDIR)$(STUBLIBDIR)
-INSTALL_MANDIR := $(DESTDIR)$(MANDIR)
+
+# Augment directories from Makefile.config / Makefile.build_config with
+# $(DESTDIR). i.e. each of these 5 directories may be overridden by the user,
+# and the compiler distribution makes no assumptions about where they are
+# relative to each other.
+INSTALL_BINDIR = $(DESTDIR)$(BINDIR)
+INSTALL_LIBDIR = $(DESTDIR)$(LIBDIR)
+INSTALL_MANDIR = $(DESTDIR)$(MANDIR)
+INSTALL_STUBLIBDIR = $(DESTDIR)$(STUBLIBDIR)
+
+# Library subdirectories. The compiler distribution does make assumptions about
+# these, and they cannot be freely overridden by the user.
+INSTALL_LIBDIR_CAML = caml
+INSTALL_LIBDIR_COMPILERLIBS = compiler-libs
+INSTALL_LIBDIR_DYNLINK = dynlink
+INSTALL_LIBDIR_FLEXDLL = flexdll
+INSTALL_LIBDIR_OCAMLDOC = ocamldoc
+INSTALL_LIBDIR_SYSTHREADS = threads
+
+INSTALL_MANDIR_PROGRAMS = man$(PROGRAMS_MAN_SECTION)
+INSTALL_MANDIR_LIBRARIES = man3
+
+INSTALL_MODE ?= install
+
+# INSTALL_MKDIR declares an installation directory
+#   $1 = section (bin, doc, lib, libexec, man, stublibs)
+#   $2 = sub-directory within $1 to create (may be omitted)
+INSTALL_MKDIR = \
+  $(call INSTALL_DESPATCH_$(INSTALL_MODE)_MKDIR,$\
+    $(strip $(1)),$\
+    $(if $(filter-out undefined,$(origin 2)),$(strip $(2))))
+
+# INSTALL_ITEM installs a single file, possibly with a different name and
+# possibly creating additional symlinks/copies
+#   $1 = source file (may include directories)
+#   $2 = section (as for INSTALL_MKDIR)
+#   $3 = directory within section (may be empty)
+#   $4 = target basename (may be empty)
+#   $5 = additional basenames (either symlinked or copied, depending on what the
+#        platform supports)
+# The $(origin n) dance is necessary to suppress warnings about undefined
+# variables.
+INSTALL_ITEM = \
+  $(call INSTALL_DESPATCH_$(INSTALL_MODE)_ITEM,$\
+    $(strip $(1)),$\
+    $(strip $(2)),$\
+    $(if $(filter-out undefined,$(origin 3)),$(strip $(3))),$\
+    $(if $(filter-out undefined,$(origin 4)),$(strip $(4))),$\
+    $(if $(filter-out undefined,$(origin 5)),$(strip $(5))))
+
+# INSTALL_ITEMS installs a series of files to a single directory
+#   $1 = source file(s) (may include directories and glob patterns)
+#   $2 = section (as for INSTALL_MKDIR)
+#   $3 = directory within section (may be omitted)
+# INSTALL_ITEMS is sometimes an alias for INSTALL_ITEM. For simplicity with
+# undefined variable warnings, INSTALL_DESPATCH_foo_ITEMS is passed 5 parameters
+# but $4 and $5 are always empty.
+INSTALL_ITEMS = \
+  $(call INSTALL_DESPATCH_$(INSTALL_MODE)_ITEMS,$\
+    $(strip $(1)),$\
+    $(strip $(2)),$\
+    $(if $(filter-out undefined,$(origin 3)),$(strip $(3))),,)
+
+# INSTALL_BEGIN and INSTALL_END are used in the root Makefile's install target
+INSTALL_BEGIN = $(INSTALL_DESPATCH_$(INSTALL_MODE)_BEGIN)
+INSTALL_END = $(INSTALL_DESPATCH_$(INSTALL_MODE)_END)
+
+# Normal installation
+INSTALL_CMD_bin = $(INSTALL_PROG)
+INSTALL_CMD_doc = $(INSTALL_DATA)
+INSTALL_CMD_lib = $(INSTALL_DATA)
+INSTALL_CMD_libexec = $(INSTALL_PROG)
+INSTALL_CMD_man = $(INSTALL_DATA)
+INSTALL_CMD_stublibs = $(INSTALL_PROG)
+
+INSTALL_SECTION_bin = $(INSTALL_BINDIR)
+INSTALL_SECTION_doc = $(INSTALL_DOCDIR)
+INSTALL_SECTION_lib = $(INSTALL_LIBDIR)
+INSTALL_SECTION_libexec = $(INSTALL_LIBDIR)
+INSTALL_SECTION_man = $(INSTALL_MANDIR)
+INSTALL_SECTION_stublibs = $(INSTALL_STUBLIBDIR)
+
+QUOTE_SINGLE = '$(subst ','\'',$(1))'
+
+INSTALL_DESPATCH_install_MKDIR = \
+  $(MKDIR) $(call QUOTE_SINGLE,$(INSTALL_SECTION_$(1))$(addprefix /,$(2)))
+
+MK_LINK = \
+  (cd "$(INSTALL_SECTION_$(2))$(addprefix /,$(3))" && \
+    $(LN) $(call QUOTE_SINGLE,$(1)) $(call QUOTE_SINGLE,$(4)))
+
+INSTALL_DESPATCH_install_ITEM = \
+  $(INSTALL_CMD_$(2)) $(1) \
+    $(call QUOTE_SINGLE,$\
+      $(INSTALL_SECTION_$(2))$(addprefix /,$(3))$(addprefix /,$(4))) \
+  $(foreach link, $(5), && \
+    $(call MK_LINK,$(if $(4),$(4),$(notdir $(1))),$(2),$(3),$(link)))
+
+INSTALL_DESPATCH_install_ITEMS = $(INSTALL_DESPATCH_install_ITEM)
+
+INSTALL_DESPATCH_install_BEGIN = @
+INSTALL_DESPATCH_install_END = @
+
+INSTALL_DESPATCH_display_MKDIR = \
+  echo $(call QUOTE_SINGLE,++ MKDIR $(INSTALL_SECTION_$(1))$(addprefix /,$(2)))
+
+MKLINK_display = \
+  echo $(call QUOTE_SINGLE,++ LN \
+         $(abspath $(INSTALL_SECTION_$(2))$(addprefix /,$(3))/$(1)) -> \
+         $(if $(4),$(4),$(notdir $(1))))
+
+INSTALL_DESPATCH_display_ITEM = \
+  echo $(call QUOTE_SINGLE,++ INSTALL $(1) \
+         $(INSTALL_SECTION_$(2))$(addprefix /,$(3))$(addprefix /,$(4))) \
+  $(foreach link, $(5), && \
+    $(call MKLINK_display,$(if $(4),$(4),$(notdir $(1))),$(2),$(3),$(link)))
+
+INSTALL_DESPATCH_display_ITEMS = $(INSTALL_DESPATCH_display_ITEM)
+
+INSTALL_DESPATCH_display_BEGIN = @
+INSTALL_DESPATCH_display_END = @
+
+INSTALL_DESPATCH_list_MKDIR =
+
+MKLINK_list = \
+  echo $(call QUOTE_SINGLE,++ \
+         $(abspath $(INSTALL_SECTION_$(2))$(addprefix /,$(3))/$\
+                     $(if $(4),$(4),$(notdir $(1)))))
+
+INSTALL_DESPATCH_list_ITEM = \
+  echo $(call QUOTE_SINGLE,++ \
+         $(abspath $(INSTALL_SECTION_$(2))$(addprefix /,$(3))/$\
+                     $(if $(4),$(4),$(notdir $(1))))) \
+  $(foreach link, $(5), && \
+    $(call MKLINK_list,$(if $(4),$(4),$(notdir $(1))),$(2),$(3),$(link)))
+
+INSTALL_DESPATCH_list_ITEMS = \
+  $(foreach file, $(wildcard $(1)), \
+    echo $(call QUOTE_SINGLE,++ \
+           $(INSTALL_SECTION_$(2))$(addprefix /,$(3))/$(notdir $(file)));) \
+  true
+
+INSTALL_DESPATCH_list_BEGIN = @
+INSTALL_DESPATCH_list_END = @
+
+OPAM_PACKAGE_NAME ?= ocaml-compiler
+
+# Generate $(OPAM_PACKAGE_NAME).install and $(OPAM_PACKAGE_NAME)-fixup.sh
+#   (INSTALL_MODE=opam)
+# opam's .install format isn't quite rich enough at present to express the
+# installation of the compiler. In particular, we can't install the doc files to
+# doc/ocaml using a .install and we can't create symlinks. The things which
+# can't be handled by the .install file are dealt with by the fixup script
+# instead.
+
+INVOKE = $(strip $(1)) $(call QUOTE_SINGLE,$(strip $(2)))
+ADD_LINE = $(call INVOKE, echo, $(2)) >> $(1)
+
+# RECORD_SYMLINK_TO_INSTALL
+#   $1 = file to install, implicitly relative to $(ROOTDIR)
+#   $2 = section
+#   $3 = subdirectory within $2 (may be empty)
+#   $4 = name to install $1 (must be specified)
+#   $5 = single name of symlink
+# If symlinks are supported, $1 is ignored and the three pieces of information
+# are recorded in $(INSTALL_MODE)-symlinks: the directory, implicitly relative
+# to the prefix, in which the symlink is to be created, the source file and name
+# of the symlink.
+# These can then be munged to a cd + ln combination in the fixup script.
+# If symlinks are not supported, $1 is instead used to create an additional copy
+# of the file, using the .install file.
+ifeq "$(firstword $(LN))" "ln"
+RECORD_SYMLINK_TO_INSTALL = \
+  $(call ADD_LINE, $(ROOTDIR)/$(INSTALL_MODE)-symlinks, \
+    $(patsubst lib%,lib,$(2))$(addprefix /,$(3)) $(4) $(5))
+else
+# Symlinks aren't available, so copy the file again using the target name
+RECORD_SYMLINK_TO_INSTALL = \
+  $(call RECORD_$(INSTALL_MODE)_ITEM_TO_INSTALL,$(1),$(2),$(3),$(5))
+endif
+
+# Process the arguments to pass to RECORD_$(INSTALL_MODE)_ITEM_TO_INSTALL:
+# - Items installed to the stublibs section need to be remapped to the stublibs
+#   subdirectory of libexec (since we install to lib/ocaml/stublibs rather than
+#   opam's default lib/stublibs)
+# - Source files must be given implicitly relative to $(ROOTDIR), so prefix with
+#   $(SUBDIR_NAME) if necessary
+# - Items installed to the lib/libexec sections will in fact be installed to
+#   lib_root/libexec_root, so remap the installation directory to ocaml (i.e. to
+#   install to lib/ocaml rather than lib)
+# - If no target basename has been explictly given, use the source's basename
+RECORD_ITEM_TO_INSTALL = \
+  $(if $(filter stublibs,$(2)),\
+    $(call RECORD_ITEM_TO_INSTALL,$\
+      $(1),libexec,stublibs$(addprefix /,$(3)),$(4),$(5)),\
+    $(call RECORD_$(INSTALL_MODE)_ITEM_TO_INSTALL,$\
+      $(addsuffix /,$(SUBDIR_NAME))$(1),$\
+      $(2),$\
+      $(if $(filter doc lib%,$(2)),ocaml$(addprefix /,$(3)),$(3)),$\
+      $(if $(4),$(4),$(notdir $(1))),$\
+      $(5)))
+
+# All files must be explicitly installed, so evaluate the wildcards and call
+# INSTALL_DESPATCH_opam_ITEM for each file.
+INSTALL_EVALUATE_GLOBS = \
+  $(foreach file, $(wildcard $(1)), \
+    $(call INSTALL_DESPATCH_$(INSTALL_MODE)_ITEM,$(file),$(2),$(3));) \
+  true
+
+ifeq "$(UNIX_OR_WIN32)" "win32"
+DO_LN = mklink $(2) $(1)
+else
+DO_LN = $(LN) $(1) $(2)
+endif
+
+INSTALL_CREATE_SYMLINKS = \
+  if test -f $(INSTALL_MODE)-symlinks; then \
+    echo 'cd "$$1"'; \
+    cut -f 1 -d ' ' $(INSTALL_MODE)-symlinks \
+      | sort -u \
+      | sed -ne "s|.*/.*|mkdir -p '&'|p"; \
+    sed -e 's|\(.*\) \(.*\) \(.*\)|$(call DO_LN,\2,\1/\3)|$\
+            $(if $(filter win32, $(UNIX_OR_WIN32)),$\
+              ;s|/|\\\\|g;s|.*|cmd /c "&"|g)' \
+      $(INSTALL_MODE)-symlinks; \
+  fi; \
+  rm -f $(INSTALL_MODE)-symlinks
+
+# RECORD_FILE_TO_INSTALL
+#   $1 = file to install, implicitly relative to $(ROOTDIR)
+#   $2 = bin/lib/libexec/man
+#   $3 = subdirectory within $2 (may be empty, but otherwise must end with "/")
+#   $4 = name to install $1 (must be specified)
+# Writes an opam .install line to the section file for $(2). Each line consists
+# of a double-quoted implicit filename relative to $(ROOTDIR) and optionally a
+# second double-quoted implicit filename relative to the $(2) for the name to
+# install the file under.
+#   e.g. "lex/ocamllex" {"ocamllex.byte"} or "expunge" {"ocaml/expunge"}
+RECORD_FILE_TO_INSTALL = \
+  $(call ADD_LINE, $(ROOTDIR)/opam-$(2), \
+    "$(1)" $(if $(3)$(filter-out $(notdir $(1)),$(4)), {"$(3)$(4)"}))
+
+# RECORD_FILE_TO_CLONE
+#   $1 = file to install, implicitly relative to $(ROOTDIR)
+#   $2 = subdirectory (may be empty, but otherwise must end with "/")
+#   $3 = name to install $1 (must be specified)
+# The compiler is installed as the ocaml package in opam, but the actual files
+# are installed from other packages (typically ocaml-compiler). For the the lib
+# directory, the lib_root and libexec_root sections allow files to be installed
+# to lib/ocaml, but there's no equivalent mechanism for the doc directory. These
+# files are recorded to be copied manually in the fixup script.
+RECORD_FILE_TO_CLONE = \
+  $(call ADD_LINE, $(ROOTDIR)/opam-clone-$(subst /,@,$(2)), $(1) $(3))
+
+# RECORD_opam_ITEM_TO_INSTALL despatches the processed arguments of
+# INSTALL_DESPATCH_opam_ITEM to the appropriate RECORD_ macro.
+RECORD_opam_ITEM_TO_INSTALL = \
+  $(if $(filter doc,$(2)),\
+    $(call RECORD_FILE_TO_CLONE,$(1),doc/$(3),$(4)), \
+    $(call RECORD_FILE_TO_INSTALL,$(1),$(2),$(addsuffix /,$(3)),$(4))) \
+  $(foreach link, $(5), && \
+    $(call RECORD_SYMLINK_TO_INSTALL,$(1),$(2),$(3),$(4),$(link)))
+
+INSTALL_DESPATCH_opam_ITEM = $(RECORD_ITEM_TO_INSTALL)
+
+INSTALL_DESPATCH_opam_ITEMS = $(INSTALL_EVALUATE_GLOBS)
+
+# INSTALL_MKDIR is ignored (opam creates them when executing the .install file)
+INSTALL_DESPATCH_opam_MKDIR =
+
+INSTALL_DESPATCH_opam_BEGIN = \
+  rm -f opam-bin opam-clone-* opam-lib opam-libexec opam-man opam-symlinks
+
+# Munge opam-bin, opam-lib, opam-libexec and opam-man into a .install file and
+# then munge opam-clone-* and opam-symlinks into the fixup script.
+INSTALL_DESPATCH_opam_END = \
+  { for i in bin lib_root libexec_root man; do \
+      if test -e opam-$${i%_root}; then \
+        echo "$$i: ["; \
+        sed -e 's/^/  /' opam-$${i%_root}; \
+        rm -f opam-$${i%_root}; \
+        echo ']'; \
+      fi; \
+    done; \
+    echo 'share_root: ['; \
+    echo '  "config.cache" {"ocaml/config.cache"}'; \
+    echo '  "config.status" {"ocaml/config.status"}'; \
+    echo ']'; \
+  } > $(OPAM_PACKAGE_NAME).install; \
+  { echo '\#!/bin/sh'; \
+    echo 'set -e'; \
+    for linkset in opam-clone-*; do \
+      if test -f $$linkset; then \
+        dir="$$(echo "$${linkset\#opam-clone-}" | sed -e 's|@|/|g')"; \
+        echo "mkdir -p \"\$$1/$$dir\""; \
+        sed -e "s|\(.*\) \(.*\)|cp \1 \"\$$1/$$dir/\2\"|" $$linkset; \
+      fi; \
+    done; \
+    rm -f opam-clone-*; \
+    $(INSTALL_CREATE_SYMLINKS); \
+  } > $(OPAM_PACKAGE_NAME)-fixup.sh
+
+# Generate $(OPAM_PACKAGE_NAME)-clone.sh (INSTALL_MODE=clone)
+
+# ld.conf is explicitly copied, rather than cloned, to allow (in principle, if
+# not in practice) the cloning installation to edit it.
+RECORD_clone_ITEM_TO_INSTALL = \
+  $(if $(filter runtime/ld.conf Makefile.config, $(1)), true, \
+    $(if $(filter libexec,$(2)), \
+      $(call RECORD_clone_ITEM_TO_INSTALL,$(1),lib,$(3),$(4),$(5)), \
+      $(call ADD_LINE, \
+        $(ROOTDIR)/clone-clone-$(2)$(addprefix @,$(subst /,@,$(3))), \
+        $(2)$(addprefix /,$(3))/$(if $(4),$(4),$(notdir $(1)))) \
+      $(foreach link, $(5), && \
+        $(call RECORD_SYMLINK_TO_INSTALL,$(1),$(2),$(3),$(4),$(link)))))
+
+INSTALL_DESPATCH_clone_ITEM = $(RECORD_ITEM_TO_INSTALL)
+
+INSTALL_DESPATCH_clone_ITEMS = $(INSTALL_EVALUATE_GLOBS)
+
+# INSTALL_MKDIR is ignored - INSTALL_DESPATCH_clone_END automatically creates
+# directories for each cp file.
+INSTALL_DESPATCH_clone_MKDIR =
+
+INSTALL_DESPATCH_clone_BEGIN = rm -f clone-clone-* clone-symlinks
+
+INSTALL_DESPATCH_clone_END = \
+  { test ! -e config.cache \
+      || echo 'share/ocaml/config.cache' > clone-clone-share@ocaml; }; \
+  { echo '\#!/bin/sh'; \
+    echo 'set -e'; \
+    echo 'mkdir -p "$$1"'; \
+    echo 'echo '\''ln -f "$$@" "$$dest/"'\'' > "$$1/clone-files"'; \
+    echo 'cat > "$$1/prefix.awk" <<"EOF"'; \
+    echo '{'; \
+    echo '  rest = $$0'; \
+    echo '  while ((p = index(rest, ENVIRON["O"]))) {'; \
+    echo '    printf "%s%s", substr(rest, 1, p-1), ENVIRON["N"]'; \
+    echo '    rest = substr(rest, p + length(ENVIRON["O"]))'; \
+    echo '  }'; \
+    echo '  print rest'; \
+    echo '}'; \
+    echo 'EOF'; \
+    for linkset in clone-clone-*; do \
+      dir="$$(echo "$${linkset\#clone-clone-}" | sed -e 's|@|/|g')"; \
+      echo "mkdir -p \"\$$1/$$dir\""; \
+      echo "dest=\"\$$1/$$dir\" xargs sh "\$$1/clone-files" <<"EOF""; \
+      cat $$linkset; \
+      echo 'EOF'; \
+    done; \
+    echo 'cp lib/ocaml/ld.conf "$$1/lib/ocaml/ld.conf"'; \
+    echo 'prefix="$$(sed -ne "s/^prefix *= *//p" lib/ocaml/Makefile.config)"'; \
+    echo 'O="$$prefix" N="$$1" awk -f "$$1/prefix.awk" \
+            lib/ocaml/Makefile.config > "$$1/lib/ocaml/Makefile.config"'; \
+    echo 'O="$$prefix" N="$$1" awk -f "$$1/prefix.awk" \
+            share/ocaml/config.status > "$$1/share/ocaml/config.status"'; \
+    echo 'rm -f "$$1/clone-files" "$$1/prefix.awk"'; \
+    rm -f clone-clone-*; \
+    $(INSTALL_CREATE_SYMLINKS); \
+  } > $(OPAM_PACKAGE_NAME)-clone.sh
 
 FLEXDLL_SUBMODULE_PRESENT := $(wildcard $(ROOTDIR)/flexdll/Makefile)
+
+IN_COREBOOT_CYCLE ?= false
 
 # Variables used to represent the OCaml runtime system
 # Most of the time, boot/ocamlrun and runtime/ocamlrun are the same.
@@ -45,6 +415,9 @@ FLEXDLL_SUBMODULE_PRESENT := $(wildcard $(ROOTDIR)/flexdll/Makefile)
 # to runtime/ocamlrun, because it's less frequently used.
 OCAMLRUN ?= $(ROOTDIR)/boot/ocamlrun$(EXE)
 NEW_OCAMLRUN ?= $(ROOTDIR)/runtime/ocamlrun$(EXE)
+
+# Standard library flags
+STDLIBFLAGS ?= -nostdlib -I $(ROOTDIR)/stdlib
 
 TEST_BOOT_OCAMLC_OPT = $(shell \
   test $(ROOTDIR)/boot/ocamlc.opt -nt $(ROOTDIR)/boot/ocamlc; \
@@ -107,6 +480,30 @@ SUBST=-e 's!%%$1%%!$(call SED_ESCAPE,$($1))!'
 # in config.mlp.  Thus, backslashes and double quotes must be escaped.
 SUBST_STRING=-e 's!%%$1%%!$(call SED_ESCAPE,$(call OCAML_ESCAPE,$($1)))!'
 
+ifeq "$(TARGET_LIBDIR_IS_RELATIVE)" "true"
+  SRCDIR_ENCODED = $(subst =,%+,$(subst :,%.,$(subst %,%$(HASH),$(SRCDIR_ABS))))
+  SRCDIR_ABS_REAL := $(shell realpath $(SRCDIR_ABS) 2>/dev/null)
+  SRCDIR_REAL_ENCODED = \
+    $(subst =,%+,$(subst :,%.,$(subst %,%$(HASH),$(SRCDIR_ABS_REAL))))
+  BUILD_PATH_PREFIX_MAP ?=
+  export BUILD_PATH_PREFIX_MAP := \
+    $(BUILD_PATH_PREFIX_MAP)$\
+      :.=$(SRCDIR_ENCODED)$\
+      $(if $(SRCDIR_REAL_ENCODED),:.=$(SRCDIR_REAL_ENCODED))
+  PRIVATE_CFLAGS = $(OC_MAP_CFLAGS)
+else
+  PRIVATE_CFLAGS =
+endif # ifeq "$(TARGET_LIBDIR_IS_RELATIVE)" "true"
+
+# Allow Makefile.cross to override the Standard Library default for the compiler
+# itself.
+HOST_LIBDIR ?= $(TARGET_LIBDIR)
+
+OC_COMMON_LINKFLAGS ?=
+OC_COMMON_LINKFLAGS += \
+  -set-runtime-default \
+    $(call QUOTE_SINGLE,standard_library_default=$(HOST_LIBDIR))
+
 # The rule to compile C files
 
 # This rule is similar to GNU make's implicit rule, except that it is more
@@ -122,8 +519,8 @@ REQUIRED_HEADERS := $(RUNTIME_HEADERS) $(wildcard *.h)
 endif
 
 %.$(O): %.c $(REQUIRED_HEADERS)
-	$(CC) -c $(OC_CFLAGS) $(CFLAGS) $(OC_CPPFLAGS) $(CPPFLAGS) \
-	  $(OUTPUTOBJ)$@ $<
+	$(CC) -c $(OC_CFLAGS) $(CFLAGS) $(PRIVATE_CFLAGS) \
+	  $(OC_CPPFLAGS) $(CPPFLAGS) $(OUTPUTOBJ)$@ $<
 
 $(DEPDIR):
 	$(MKDIR) $@
@@ -163,12 +560,34 @@ OCAMLYACCFLAGS ?=
 
 SAK = $(ROOTDIR)/runtime/sak$(EXE)
 
-# stdlib/StdlibModules cannot be include'd unless $(SAK) has been built. These
-# two rules add that dependency. They have to be pattern rules since
-# Makefile.common is included before default targets.
-$(ROOTDIR)/%/sak$(EXE):
-	$(MAKE) -C $(ROOTDIR)/$* sak$(EXE)
+# $(ROOTDIR)/ocamlc needs -launch-method to be given explicitly as its default
+# values are those for the target (cf. --with-target-sh and TARGET_BINDIR).
+BYTECODE_LAUNCHER_FLAGS = \
+  -launch-method $(call QUOTE_SINGLE,$(LAUNCH_METHOD) $(BINDIR)) \
+  -runtime-search $(if $(RUNTIME_SEARCH),$(RUNTIME_SEARCH),disable)
 
-ifneq "$(REQUIRES_CONFIGURATION)" ""
-$(ROOTDIR)/%/StdlibModules: $(SAK) ;
+MAYBE_ADD_BYTECODE_LAUNCHER_FLAGS = \
+  $(if $(filter -custom, $(1)),,\
+    -use-prims $(ROOTDIR)/runtime/primitives $(BYTECODE_LAUNCHER_FLAGS))
+
+LINK_BYTECODE_PROGRAM =\
+  $(CAMLC) $(OC_COMMON_LINKFLAGS) \
+    $(call MAYBE_ADD_BYTECODE_LAUNCHER_FLAGS, \
+      $(OC_COMMON_LINKFLAGS) $(OC_BYTECODE_LINKFLAGS)) $(OC_BYTECODE_LINKFLAGS)
+
+# ocamlc has several mechanisms for linking a bytecode image to the runtime
+# which executes it. The exact mechanism depends on the platform and the precise
+# location of the runtime. The boot compiler (boot/ocamlc) therefore needs this
+# additional information, which comes from the stdlib build and is copied into
+# boot/ as part of coldstart. See read_runtime_launch_info in
+# bytecomp/bytelink.ml for further details.
+HEADER_NAME = camlheader
+
+ifeq "$(UNIX_OR_WIN32)" "win32"
+# Ensure that no command can create Cygwin symbolic links by ensuring that
+# symlink(2) will fail if native NTFS symlinks aren't available.
+export CYGWIN := $(strip \
+  $(filter-out winsymlinks winsymlinks:%, $(CYGWIN)) winsymlinks:nativestrict)
+export MSYS := $(strip \
+  $(filter-out winsymlinks winsymlinks:%, $(MSYS)) winsymlinks:nativestrict)
 endif
